title: Roshan Nellore Prasad
logo: docs/IMG_2447.JPG
description: Security Engineer | Movie Buff | Cricketer
bio: >
  Hello :) Thank you for being here to learn about me. Just like a vigilant wicketkeeper guarding the stumps, my work reflects a commitment to Security Principles and Architecture.
  My love for security began during high school when my grandfather became a victim of a Vishing attack. From then, I have always been a cyber speaker to my friends and family, teaching them "what to do" and "what not" in the digital landscape. I started my cyber journey working on an undergrad project with Multi-factor and Captchas, and later worked on breaking and safeguarding systems in my Grad school.
  I love to stay updated with security news and work on challenges that make my brain hover. Besides techie stuff, I love to play cricket and watch movies.
# show_downloads: true
theme: jekyll-theme-minimal
